import faker from "faker";

/* prettier-ignore */
export const fakeProps = [
  { name: "zipCode", value: faker.address.zipCode(), type: "text" },
  { name: "city", value: faker.address.city(), type: "text" },
  { name: "cityPrefix", value: faker.address.cityPrefix(), type: "text" },
  { name: "citySuffix", value: faker.address.citySuffix(), type: "text" },
  { name: "streetName", value: faker.address.streetName(), type: "text" },
  { name: "streetAddress", value: faker.address.streetAddress(), type: "text" },
  { name: "streetSuffix", value: faker.address.streetSuffix(), type: "text" },
  { name: "streetPrefix", value: faker.address.streetPrefix(), type: "text" },
  { name: "secondaryAddress", value: faker.address.secondaryAddress(), type: "text" },
  { name: "county", value: faker.address.county(), type: "text" },
  { name: "country", value: faker.address.country(), type: "text" },
  { name: "countryCode", value: faker.address.countryCode(), type: "text" },
  { name: "state", value: faker.address.state(), type: "text" },
  { name: "stateAbbr", value: faker.address.stateAbbr(), type: "text" },
  { name: "latitude", value: faker.address.latitude(), type: "text" },
  { name: "longitude", value: faker.address.longitude(), type: "text" },
  { name: "color", value: faker.commerce.color(), type: "text" },
  { name: "department", value: faker.commerce.department(), type: "text" },
  { name: "productName", value: faker.commerce.productName(), type: "text" },
  { name: "price", value: faker.commerce.price(), type: "text" },
  { name: "productAdjective", value: faker.commerce.productAdjective(), type: "text" },
  { name: "productMaterial", value: faker.commerce.productMaterial(), type: "text" },
  { name: "email", value: faker.internet.email(), type: "email" },
  { name: "exampleEmail", value: faker.internet.exampleEmail(), type: "email" },
  { name: "userName", value: faker.internet.userName(), type: "text" },
  { name: "protocol", value: faker.internet.protocol(), type: "text" },
  { name: "url", value: faker.internet.url(), type: "url" },
  { name: "domainName", value: faker.internet.domainName(), type: "text" },
  { name: "domainSuffix", value: faker.internet.domainSuffix(), type: "text" },
  { name: "domainWord", value: faker.internet.domainWord(), type: "text" },
  { name: "ip", value: faker.internet.ip(), type: "url" },
  { name: "ipv6", value: faker.internet.ipv6(), type: "url" },
  { name: "userAgent", value: faker.internet.userAgent(), type: "text" },
  { name: "color", value: faker.internet.color(), type: "text" },
  { name: "mac", value: faker.internet.mac(), type: "text" },
  { name: "password", value: faker.internet.password(), type: "text" },
  { name: "commerceProduct", value: faker.commerce.product(), type: "text" },
  { name: "abbreviation", value: faker.hacker.abbreviation(), type: "text" },
  { name: "adjective", value: faker.hacker.adjective(), type: "text" },
  { name: "noun", value: faker.hacker.noun(), type: "text" },
  { name: "verb", value: faker.hacker.verb(), type: "text" },
  { name: "ingverb", value: faker.hacker.ingverb(), type: "text" },
  { name: "phrase", value: faker.hacker.phrase(), type: "text" },
  { name: "image", value: faker.image.image, type: "image" },
  { name: "avatar", value: faker.image.avatar, type: "image" },
  { name: "imageUrl", value: faker.image.imageUrl, type: "image" },
  { name: "abstract", value: faker.image.abstract, type: "image" },
  { name: "animals", value: faker.image.animals, type: "image" },
  { name: "business", value: faker.image.business, type: "image" },
  { name: "cats", value: faker.image.cats, type: "image" },
  { name: "city", value: faker.image.city, type: "image" },
  { name: "food", value: faker.image.food, type: "image" },
  { name: "nightlife", value: faker.image.nightlife, type: "image" },
  { name: "fashion", value: faker.image.fashion, type: "image" },
  { name: "people", value: faker.image.people, type: "image" },
  { name: "nature", value: faker.image.nature, type: "image" },
  { name: "sports", value: faker.image.sports, type: "image" },
  { name: "technics", value: faker.image.technics, type: "image" },
  { name: "transport", value: faker.image.transport, type: "image" },
  { name: "dataUri", value: faker.image.dataUri, type: "image" },
  { name: "past", value: faker.date.past(), type: "date" },
  { name: "future", value: faker.date.future(), type: "date" },
  { name: "recent", value: faker.date.recent(), type: "date" },
  { name: "soon", value: faker.date.soon(), type: "date" },
  { name: "month", value: faker.date.month(), type: "date" },
  { name: "weekday", value: faker.date.weekday(), type: "text" },
  { name: "account", value: faker.finance.account(), type: "text" },
  { name: "accountName", value: faker.finance.accountName(), type: "text" },
  { name: "mask", value: faker.finance.mask(), type: "text" },
  { name: "amount", value: faker.finance.amount(), type: "text" },
  { name: "transactionType", value: faker.finance.transactionType(), type: "text" },
  { name: "currencyCode", value: faker.finance.currencyCode(), type: "text" },
  { name: "currencyName", value: faker.finance.currencyName(), type: "text" },
  { name: "currencySymbol", value: faker.finance.currencySymbol(), type: "text" },
  { name: "bitcoinAddress", value: faker.finance.bitcoinAddress(), type: "text" },
  { name: "ethereumAddress", value: faker.finance.ethereumAddress(), type: "text" },
  { name: "iban", value: faker.finance.iban(), type: "text" },
  { name: "bic", value: faker.finance.bic(), type: "text" },

];

export const getType = prop => {
  if (Array.isArray(prop)) {
    return `${typeof prop}[]`;
  }
  return typeof prop;
};
